name: "Setup virtualization"
description: "Setup virtualization on the runner"
author: "Gerard Braad <me@gbraad.nl>"
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update
        sudo apt install -y \
          qemu-kvm qemu-user libvirt-daemon libvirt-daemon-system virtiofsd virt-manager
        sudo usermod -a -G kvm $USER
        sudo usermod -a -G libvirt $USER
        # prevents the user having to re-login
        sudo chmod 666 /dev/kvm
      shell: bash
